apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: temperature-worker-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8e6d77a3-0d6a-44d0-aee1-d6dcc9c07ab9"
    keyvaultName: "wellopskeyvault"
    tenantId: "d4ab9b9c-7c72-4258-aba6-110fc80784e6"
    objects: |
      array:
        - |
          objectName: RABBITMQ-DEFAULT-USER
          objectType: secret
        - |
          objectName: RABBITMQ-DEFAULT-PASS
          objectType: secret
        - |
          objectName: RABBITMQ-HOST
          objectType: secret
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
        - |
          objectName: POSTGRES-DB
          objectType: secret
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret
  secretObjects:
    - secretName: temperature-worker-secret
      type: Opaque
      data:
        - objectName: RABBITMQ-DEFAULT-USER
          key: RABBITMQ_DEFAULT_USER
        - objectName: RABBITMQ-DEFAULT-PASS
          key: RABBITMQ_DEFAULT_PASS
        - objectName: RABBITMQ-HOST
          key: RABBITMQ_HOST
        - objectName: POSTGRES-USER
          key: POSTGRES_USER
        - objectName: POSTGRES-PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: POSTGRES-DB
          key: POSTGRES_DB
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-PORT
          key: DB_PORT
