apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: simulator-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8e6d77a3-0d6a-44d0-aee1-d6dcc9c07ab9"
    keyvaultName: "wellopskeyvault"
    tenantId: "d4ab9b9c-7c72-4258-aba6-110fc80784e6"
    objects: |
      array:
        - |
          objectName: RABBITMQ-DEFAULT-USER
          objectType: secret
        - |
          objectName: RABBITMQ-DEFAULT-PASS
          objectType: secret
        - |
          objectName: RABBITMQ-HOST
          objectType: secret
        - |
          objectName: RABBITMQ-QUEUE-NAME
          objectType: secret
  secretObjects:
    - secretName: simulator-secret
      type: Opaque
      data:
        - objectName: RABBITMQ-DEFAULT-USER
          key: RABBITMQ_DEFAULT_USER
        - objectName: RABBITMQ-DEFAULT-PASS
          key: RABBITMQ_DEFAULT_PASS
        - objectName: RABBITMQ-HOST
          key: RABBITMQ_HOST
        - objectName: RABBITMQ-QUEUE-NAME
          key: RABBITMQ_QUEUE_NAME
